### ISSUE TITLE
--files-from 使用方法的解释

### ISSUE THREAD

**Issue by sghng** [aliyun/ossutil#258]
`--files-from` 这个 flag 的使用方法在文档里没有解释清楚，我的使用场景如下：

```yaml
- name: Deploy - delete files
  run: |
    ./ossutil rm $BUCKET -rf --files-from delete-list

- name: Deploy - update files
  run: |
    ./ossutil cp ./dist $BUCKET -f --files-from update-list 
```

这两个命令都报错，exit code 1，没有任何其他解释，不知道使用方法对不对。`update-list`中的文件路径是相对于 `./dist` 的，应该是工具开发者的本意。尝试过把 flag 移动到紧随 ossuitl 之后，依然无法正常使用
